### ISSUE TITLE
Unable to boot the installer it stucks

### ISSUE THREAD

**Issue by shivvrat12** [BluePurplePro/Dell-Latitude-E5430-Hackintosh#1]
On the same latitude laptop the installer is not even launching resulting in a mismatched text showing.
![17348714964803114488501945454875](https://github.com/user-attachments/assets/aeda24e1-ba92-4954-91c4-6e4e040c1935)

**Comment by BluePurplePro** [comment]
Run [OCSysInfo](https://github.com/KernelWanderers/OCSysInfo) on Windows and upload your specs here

**Comment by shivvrat12** [comment]
Thanks I have resolved the error by putting the EFI which you've provided but the wifi and bluetooth is not working because I don't have intel card i have Broadcom chipset anyways the purpose of installating mac isn't fulfilled because I just wanted to use Xcode which is not supported on catalina I tried installing sonoma with same EFI but didn't get success in it.

**Comment by BluePurplePro** [comment]
Theoretically Ivy Bridge laptops can boot to Monterey/Ventura/Sonoma/Sequoia with [OCLP's patches](https://dortania.github.io/OpenCore-Legacy-Patcher/) (they have no support for hackintoshes, so you're on your own), though this requires understanding OpenCore EFI function. I highly suggest you make the EFI using [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/) first

**Comment by BluePurplePro** [comment]
The last Xcode version that supports Catalina is [12.4](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_4-release-notes). I only have a copy of [Xcode 11.3.1](https://85lbb2-my.sharepoint.com/:u:/g/personal/bluepurple_85lbb2_onmicrosoft_com/Ed6UbAdJy_NBrRmSZRAtp8oBejTYCnUywVGxDSdTNoRasg?e=tjCXuN) though, give it a try if you want (set the date to 2019 before installing)
If your work depends on Xcode, buying an M4 Mac would be the best in this case
